#  project encoding
project:
  encoding:
    charset: utf-8
    enabled: true


# 注册中心
eureka:
  #  server:
  #    enable-self-preservation: false  #自我保护机制 (不推荐关闭)
  client:
    service-url:
      defaultZone: http://qlhx:qlhx123456@localhost:12001/eureka/
  #      defaultZone: http://eureka1.com:12001/eureka/,http://eureka2.com:12002/eureka/,http://eureka3.com:12003/eureka/
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port} #ip:port
    prefer-ip-address: true #显示IP


server:
  name:
    base: base-service
    control: service
    device: service
    door: door-service
    facedevice: faceservice
    logger: gateway-service
    wechat: service
    auth: service
  port:
    base: 16001
    control: 16002
    device: 16003
    door: 16004
    facedevice: 16005
    logger: 16007
    wechat: 16008
    auth: 1609

web:
  name:
    base: web-base-service
    control: web-service
    device: web-service
    door: web-door-service
    facedevice: web-faceservice
    gateway: web-gateway-service
    logger: web-service
    wechat: web-service
    auth: web-service
  port:
    base: 16011
    control: 16012
    device: 16013
    door: 16014
    facedevice: 16015
    gateway: 16016
    logger: 16017
    wechat: 16018
    auth: 16019



hystrix:
    command:
      default:
        execution:
          isolation:
            semaphore:
              maxConcurrentRequests: 5000
            thread:
              timeoutInMilliseconds: 30000
          timeout:
            enabled: true
    threadpool:
      default:
        coresize: 200
        maxQueueSize: 100000
        queueSizeRejectionThreshold: 100000

#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000



spring:
  datasource:
      sql-script-encoding: ${project.encoding.charset}
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat,wall,log4j
      initialSize: 5
      logSlowSql: true
      maxActive: 20
      maxWait: 60000
      minEvictableIdleTimeMillis: 300000
      minIdle: 5
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 60000
      validationQuery: SELECT 1 FROM DUAL
  transaction:
      expression: execution (* com.qlhx.**.realize.service.**.impl.*.*(..))

  http:
    encoding:
      charset: ${project.encoding.charset}
      enabled: ${project.encoding.enabled}
  redis:
    redis-host: 202.142.28.62
    redis-port: 61379
    redis-password: '{cipher}AQBKe8nd7qi1jzXZhTST9xgt6iml33GBAcF1jw0+k4REHsNczlmygwx2omItxK2GUeQs6yCiQWSqQIHAHbpCn2Pi3YsjYWp3H5Px7i8/uj0czvmU9kBpkzvuMlYqYTKvj+LKl4/+DwnZ1AYFJBREcNN5fLJ/UfBOW+/1lqI6q+vggT34CcVpIs92JW8WaAVN81c0xmHC2rzKAfQlxOfhAYOu59bKptqIAAwxzg4Aea83n6kcg9KYlZ779hDzG/S2cIo4Zi0lRfNZ0xMkfKNsVtuGqayw0lTjs/pdICea/qEancNNR2AXu7zbcxtRUtVPXCnKyGFQevA9Nm4HnoyhigNjXvsTdXKgIV0FAL5EMBuTe3p4k8XPzQiQ1u37Uu0reZk='
    redis-timeout: 5000
    redis-database: 0
  rabbitmq:
    rabbitmq-host: 202.142.28.62
    rabbitmq-port: 5673
    rabbitmq-username: '{cipher}AQCcTOkj4yXHQsNbH+UqEfZItOm8JYXHuH6WAIY//r9r3EURIbmMCQQFja6qqikYx36pZKsIo16l0/rZlx3QMfDYGFXMyW7unSJitrF5slls22MRcVdDyxK3u+elJ8RIbL40f7q6UT3OH9Aeg9NfH5pzZWPLc/m1q/0zgd3Cx7KnfHbLRzKzifPh+ab8Fwjk34LOGVNnQ67ZEVFb7QvvbRBYWFnvXobBlYMCyuZk7EpicG6gcYNVgFF/BRYDEJKCw3+F3Mqoj9toMOnWqm6JH1DKR1fYZRXdLn0g9eTMXBhnF5bdB9iPqg2a2WKZ+0nKgqj0u34mArgo9C9GuTzEAgU8izrTDpbag/inRCczvkPbRK920RN4v+bvUXAg44ToiJo='
    rabbitmq-password: '{cipher}AQCFVTj6YJuDTNNwop542YQO/HLYknwfPhy+69a6+TWIb5kXuADq3NWNiapW8k295cpTLwwyuFiw5mN+rgi+wc91duud5ePZqJBb9J5zySplzmZHlLYs856NuSd9fP6pcVaP6Jf7uVz69c7AfU/Cc4kNNPEceSGhyada9KjI2ZGnfx323ZgAETWzaqIf26/9uQT1sFTIVvXWHcIKhjeGl6kvJlxvzPbJBM4QB81zTGlM091XsLt5Yf3gzLEdLG/VDsKcBYNULZlaTIabd1V/hVTg3uNho71KlJDkMK0PJfoK1fmVgWpMlV+2FUm+zLQsD34rhqZrp3JuLPchm64FbAmrqJZEQUFqOl6uDZxqV5YsiXrzaxwEE4APEiZ6/pLgQc8='



database:
  datasource:
    auth:
      dbName: aivms5
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://202.142.28.62:32770/aivms5
      username: postgres
      password: 123456
   login:
    name: qlhx
    password: qlhx123456
