#  project encoding
project:
  encoding:
    charset: utf-8
    enabled: true
# 注册中心
eureka:
  #  server:
  #    enable-self-preservation: false  #自我保护机制 (不推荐关闭)
  client:
    service-url:
      defaultZone: http://202.142.28.62:12001/eureka/
  #      defaultZone: http://eureka1.com:12001/eureka/,http://eureka2.com:12002/eureka/,http://eureka3.com:12003/eureka/
  instance:
    instance-id: ${spring.application.name}-${server.port} #更改主机显示名称
    prefer-ip-address: true #显示IP


server:
  name:
    base: base-service
    control: control-service
    device: device-service
    door: door-service
    facedevice: facedevice-service
    logger: gateway-service
    wechat: wechat-service
  port:
    base: 16001
    control: 16002
    device: 16003
    door: 16004
    facedevice: 16005
    logger: 16007
    wechat: 16008

web:
  name:
    base: web-base-service
    control: web-control-service
    device: web-device-service
    door: web-door-service
    facedevice: web-facedevice-service
    gateway: web-gateway-service
    logger: web-logger-service
    wechat: web-wechat-service
  port:
    base: 16011
    control: 16012
    device: 16013
    door: 16014
    facedevice: 16015
    gateway: 16016
    logger: 16017
    wechat: 16018



hystrix:
    command:
        default:
            execution:
              timeout:
                enabled: true
              isolation:
                    thread:
                        timeoutInMilliseconds: 30000
#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000



spring:
  datasource:
      sql-script-encoding: ${project.encoding.charset}
      type: com.alibaba.druid.pool.DruidDataSource
  http:
    encoding:
      charset: ${project.encoding.charset}
      enabled: ${project.encoding.enabled}
  redis:
    redis-host: 202.142.28.62
    redis-port: 61379
    redis-password: '{cipher}AQBKe8nd7qi1jzXZhTST9xgt6iml33GBAcF1jw0+k4REHsNczlmygwx2omItxK2GUeQs6yCiQWSqQIHAHbpCn2Pi3YsjYWp3H5Px7i8/uj0czvmU9kBpkzvuMlYqYTKvj+LKl4/+DwnZ1AYFJBREcNN5fLJ/UfBOW+/1lqI6q+vggT34CcVpIs92JW8WaAVN81c0xmHC2rzKAfQlxOfhAYOu59bKptqIAAwxzg4Aea83n6kcg9KYlZ779hDzG/S2cIo4Zi0lRfNZ0xMkfKNsVtuGqayw0lTjs/pdICea/qEancNNR2AXu7zbcxtRUtVPXCnKyGFQevA9Nm4HnoyhigNjXvsTdXKgIV0FAL5EMBuTe3p4k8XPzQiQ1u37Uu0reZk='
    redis-timeout: 5000
    redis-database: 0
  rabbitmq:
    rabbitmq-host: 202.142.28.62
    rabbitmq-port: 5673
    rabbitmq-username: '{cipher}AQCcTOkj4yXHQsNbH+UqEfZItOm8JYXHuH6WAIY//r9r3EURIbmMCQQFja6qqikYx36pZKsIo16l0/rZlx3QMfDYGFXMyW7unSJitrF5slls22MRcVdDyxK3u+elJ8RIbL40f7q6UT3OH9Aeg9NfH5pzZWPLc/m1q/0zgd3Cx7KnfHbLRzKzifPh+ab8Fwjk34LOGVNnQ67ZEVFb7QvvbRBYWFnvXobBlYMCyuZk7EpicG6gcYNVgFF/BRYDEJKCw3+F3Mqoj9toMOnWqm6JH1DKR1fYZRXdLn0g9eTMXBhnF5bdB9iPqg2a2WKZ+0nKgqj0u34mArgo9C9GuTzEAgU8izrTDpbag/inRCczvkPbRK920RN4v+bvUXAg44ToiJo='
    rabbitmq-password: '{cipher}AQCFVTj6YJuDTNNwop542YQO/HLYknwfPhy+69a6+TWIb5kXuADq3NWNiapW8k295cpTLwwyuFiw5mN+rgi+wc91duud5ePZqJBb9J5zySplzmZHlLYs856NuSd9fP6pcVaP6Jf7uVz69c7AfU/Cc4kNNPEceSGhyada9KjI2ZGnfx323ZgAETWzaqIf26/9uQT1sFTIVvXWHcIKhjeGl6kvJlxvzPbJBM4QB81zTGlM091XsLt5Yf3gzLEdLG/VDsKcBYNULZlaTIabd1V/hVTg3uNho71KlJDkMK0PJfoK1fmVgWpMlV+2FUm+zLQsD34rhqZrp3JuLPchm64FbAmrqJZEQUFqOl6uDZxqV5YsiXrzaxwEE4APEiZ6/pLgQc8='



database:
  datasource:
    base:
      base-dbName: '{cipher}AQAxoI0k4djrnhdrffTg9ILmqhBo6d4XXI/buEBZSszfFde3zJrh4ZMUGl4jRDo3mJGc46tcahJuKkmDOFN0c3RVWD6ieuSd9KVvaNGjKPtg7kZ0phRejDJVI1yCbXSPDUqW6w60dIfYZMELd6tGHnS3bXHTI3I3Knfa75a7W/jbyf1vRMWwJDWSL+EmtSE8nDZQaUcBabRpPIFJ2g4oxTnro+oUezV8jQjPGdBc5HlfL5t5Fi3WKlmiRRAxJQGgH8LvP7Dh1COjkYFGvk3hD+7OTaJhrK4sk58iXBAj7rwlTTQIv2NRdmYpA/MBUpcSUKkO9+3qNn5gX5iNzi5w3oZn68k0Ucid52dDFLZYg2kXXQF7z7VB67eCw8U/Rsy6JhI='
      base-driver-class-name: com.mysql.cj.jdbc.Driver
      base-url: jdbc:mysql://202.142.28.62:33007/${database.datasource.base.base-dbName}?useSSL=true&serverTimezone=UTC&characterEncoding=utf8&useUnicode=true
      base-username: '{cipher}AQANeaUl85JhUJjxe5gy9vGnqfnvm2p5M0cKqDqAfeOzHvKr3OVgNinnwJZso455XaVMRbgGWhAQra6lzYihhUeJYKHjm4+BF3Onr8hwdH433uF4P28u13IfrG1gjZGbzhst7k3QkW/qggZAFQB6l31lAtT4+0DKj+1HYVz0UIKMhijsVvCaPyw4s8IJnMXWlf6jMLdHoB1LRgWJ21IV7v+UfE4XtZOfQhM3wCL6cGuwj1tfMCcOlgTs1AjUeTUzTAUPX1hXxCviS8JBAhDir2hmGmQxWioAf6e89/1TONLIpknd9aRW5KM4SuQfayQTi1T6m3fyNw9StyDvUezMKsOin2naXFfrnOQhUa+K4aViBXxEoccp+z26ivzmUJTbNGI='
      base-password: '{cipher}AQCB+iRpVT8Lrf6pW9tg6140vcgs9pgMcKoHuhd12Zb5//KdRH1s514+udc+8WARKg48E09C8Z4OV9VeBBPX8N/Sk+TYGuHP9HUG+DlY3OhesnaHz9gqurvkNma/JG1qSHkxR+TKdcFzz62vxrht+ZEAU02lthsBxCzHYcrhv62LbqMhIpHYqC9Hk86HYC0FklqtR8JNbRtb6RprY9jHHe47VNIoyoR4vpIiJvbyFAn2fMsLDKI0+R6AZv7NRYAiE8qY45JK9qIu13//YbWdKJ1jKlL0uOFVSVzx1VsTt/8pguYE5LTwI55tEuTJFATdeAyS84Wdnh9y9uHofMGYDevQIPwsbxUVRzTABhVTEMFjOpH2FEsYFrCIV59ZVcwbouM='
    door:
      door-dbName: '{cipher}AQAxoI0k4djrnhdrffTg9ILmqhBo6d4XXI/buEBZSszfFde3zJrh4ZMUGl4jRDo3mJGc46tcahJuKkmDOFN0c3RVWD6ieuSd9KVvaNGjKPtg7kZ0phRejDJVI1yCbXSPDUqW6w60dIfYZMELd6tGHnS3bXHTI3I3Knfa75a7W/jbyf1vRMWwJDWSL+EmtSE8nDZQaUcBabRpPIFJ2g4oxTnro+oUezV8jQjPGdBc5HlfL5t5Fi3WKlmiRRAxJQGgH8LvP7Dh1COjkYFGvk3hD+7OTaJhrK4sk58iXBAj7rwlTTQIv2NRdmYpA/MBUpcSUKkO9+3qNn5gX5iNzi5w3oZn68k0Ucid52dDFLZYg2kXXQF7z7VB67eCw8U/Rsy6JhI='
      door-driver-class-name: com.mysql.cj.jdbc.Driver
      door-url: jdbc:mysql://202.142.28.62:33007/${database.datasource.door.door-dbName}?useSSL=true&serverTimezone=UTC&characterEncoding=utf8&useUnicode=true
      door-username: '{cipher}AQANeaUl85JhUJjxe5gy9vGnqfnvm2p5M0cKqDqAfeOzHvKr3OVgNinnwJZso455XaVMRbgGWhAQra6lzYihhUeJYKHjm4+BF3Onr8hwdH433uF4P28u13IfrG1gjZGbzhst7k3QkW/qggZAFQB6l31lAtT4+0DKj+1HYVz0UIKMhijsVvCaPyw4s8IJnMXWlf6jMLdHoB1LRgWJ21IV7v+UfE4XtZOfQhM3wCL6cGuwj1tfMCcOlgTs1AjUeTUzTAUPX1hXxCviS8JBAhDir2hmGmQxWioAf6e89/1TONLIpknd9aRW5KM4SuQfayQTi1T6m3fyNw9StyDvUezMKsOin2naXFfrnOQhUa+K4aViBXxEoccp+z26ivzmUJTbNGI='
      door-password: '{cipher}AQCB+iRpVT8Lrf6pW9tg6140vcgs9pgMcKoHuhd12Zb5//KdRH1s514+udc+8WARKg48E09C8Z4OV9VeBBPX8N/Sk+TYGuHP9HUG+DlY3OhesnaHz9gqurvkNma/JG1qSHkxR+TKdcFzz62vxrht+ZEAU02lthsBxCzHYcrhv62LbqMhIpHYqC9Hk86HYC0FklqtR8JNbRtb6RprY9jHHe47VNIoyoR4vpIiJvbyFAn2fMsLDKI0+R6AZv7NRYAiE8qY45JK9qIu13//YbWdKJ1jKlL0uOFVSVzx1VsTt/8pguYE5LTwI55tEuTJFATdeAyS84Wdnh9y9uHofMGYDevQIPwsbxUVRzTABhVTEMFjOpH2FEsYFrCIV59ZVcwbouM='
    control:
      control-dbName: '{cipher}AQAxoI0k4djrnhdrffTg9ILmqhBo6d4XXI/buEBZSszfFde3zJrh4ZMUGl4jRDo3mJGc46tcahJuKkmDOFN0c3RVWD6ieuSd9KVvaNGjKPtg7kZ0phRejDJVI1yCbXSPDUqW6w60dIfYZMELd6tGHnS3bXHTI3I3Knfa75a7W/jbyf1vRMWwJDWSL+EmtSE8nDZQaUcBabRpPIFJ2g4oxTnro+oUezV8jQjPGdBc5HlfL5t5Fi3WKlmiRRAxJQGgH8LvP7Dh1COjkYFGvk3hD+7OTaJhrK4sk58iXBAj7rwlTTQIv2NRdmYpA/MBUpcSUKkO9+3qNn5gX5iNzi5w3oZn68k0Ucid52dDFLZYg2kXXQF7z7VB67eCw8U/Rsy6JhI='
      control-driver-class-name: com.mysql.cj.jdbc.Driver
      control-url: jdbc:mysql://202.142.28.62:33007/${database.datasource.control.control-dbName}?useSSL=true&serverTimezone=UTC&characterEncoding=utf8&useUnicode=true
      control-username: '{cipher}AQANeaUl85JhUJjxe5gy9vGnqfnvm2p5M0cKqDqAfeOzHvKr3OVgNinnwJZso455XaVMRbgGWhAQra6lzYihhUeJYKHjm4+BF3Onr8hwdH433uF4P28u13IfrG1gjZGbzhst7k3QkW/qggZAFQB6l31lAtT4+0DKj+1HYVz0UIKMhijsVvCaPyw4s8IJnMXWlf6jMLdHoB1LRgWJ21IV7v+UfE4XtZOfQhM3wCL6cGuwj1tfMCcOlgTs1AjUeTUzTAUPX1hXxCviS8JBAhDir2hmGmQxWioAf6e89/1TONLIpknd9aRW5KM4SuQfayQTi1T6m3fyNw9StyDvUezMKsOin2naXFfrnOQhUa+K4aViBXxEoccp+z26ivzmUJTbNGI='
      control-password: '{cipher}AQCB+iRpVT8Lrf6pW9tg6140vcgs9pgMcKoHuhd12Zb5//KdRH1s514+udc+8WARKg48E09C8Z4OV9VeBBPX8N/Sk+TYGuHP9HUG+DlY3OhesnaHz9gqurvkNma/JG1qSHkxR+TKdcFzz62vxrht+ZEAU02lthsBxCzHYcrhv62LbqMhIpHYqC9Hk86HYC0FklqtR8JNbRtb6RprY9jHHe47VNIoyoR4vpIiJvbyFAn2fMsLDKI0+R6AZv7NRYAiE8qY45JK9qIu13//YbWdKJ1jKlL0uOFVSVzx1VsTt/8pguYE5LTwI55tEuTJFATdeAyS84Wdnh9y9uHofMGYDevQIPwsbxUVRzTABhVTEMFjOpH2FEsYFrCIV59ZVcwbouM='
    device:
      device-dbName: '{cipher}AQAxoI0k4djrnhdrffTg9ILmqhBo6d4XXI/buEBZSszfFde3zJrh4ZMUGl4jRDo3mJGc46tcahJuKkmDOFN0c3RVWD6ieuSd9KVvaNGjKPtg7kZ0phRejDJVI1yCbXSPDUqW6w60dIfYZMELd6tGHnS3bXHTI3I3Knfa75a7W/jbyf1vRMWwJDWSL+EmtSE8nDZQaUcBabRpPIFJ2g4oxTnro+oUezV8jQjPGdBc5HlfL5t5Fi3WKlmiRRAxJQGgH8LvP7Dh1COjkYFGvk3hD+7OTaJhrK4sk58iXBAj7rwlTTQIv2NRdmYpA/MBUpcSUKkO9+3qNn5gX5iNzi5w3oZn68k0Ucid52dDFLZYg2kXXQF7z7VB67eCw8U/Rsy6JhI='
      device-driver-class-name: com.mysql.cj.jdbc.Driver
      device-url: jdbc:mysql://202.142.28.62:33007/${database.datasource.device.device-dbName}?useSSL=true&serverTimezone=UTC&characterEncoding=utf8&useUnicode=true
      device-username: '{cipher}AQANeaUl85JhUJjxe5gy9vGnqfnvm2p5M0cKqDqAfeOzHvKr3OVgNinnwJZso455XaVMRbgGWhAQra6lzYihhUeJYKHjm4+BF3Onr8hwdH433uF4P28u13IfrG1gjZGbzhst7k3QkW/qggZAFQB6l31lAtT4+0DKj+1HYVz0UIKMhijsVvCaPyw4s8IJnMXWlf6jMLdHoB1LRgWJ21IV7v+UfE4XtZOfQhM3wCL6cGuwj1tfMCcOlgTs1AjUeTUzTAUPX1hXxCviS8JBAhDir2hmGmQxWioAf6e89/1TONLIpknd9aRW5KM4SuQfayQTi1T6m3fyNw9StyDvUezMKsOin2naXFfrnOQhUa+K4aViBXxEoccp+z26ivzmUJTbNGI='
      device-password: '{cipher}AQCB+iRpVT8Lrf6pW9tg6140vcgs9pgMcKoHuhd12Zb5//KdRH1s514+udc+8WARKg48E09C8Z4OV9VeBBPX8N/Sk+TYGuHP9HUG+DlY3OhesnaHz9gqurvkNma/JG1qSHkxR+TKdcFzz62vxrht+ZEAU02lthsBxCzHYcrhv62LbqMhIpHYqC9Hk86HYC0FklqtR8JNbRtb6RprY9jHHe47VNIoyoR4vpIiJvbyFAn2fMsLDKI0+R6AZv7NRYAiE8qY45JK9qIu13//YbWdKJ1jKlL0uOFVSVzx1VsTt/8pguYE5LTwI55tEuTJFATdeAyS84Wdnh9y9uHofMGYDevQIPwsbxUVRzTABhVTEMFjOpH2FEsYFrCIV59ZVcwbouM='
    facedevice:
      device-dbName: '{cipher}AQAxoI0k4djrnhdrffTg9ILmqhBo6d4XXI/buEBZSszfFde3zJrh4ZMUGl4jRDo3mJGc46tcahJuKkmDOFN0c3RVWD6ieuSd9KVvaNGjKPtg7kZ0phRejDJVI1yCbXSPDUqW6w60dIfYZMELd6tGHnS3bXHTI3I3Knfa75a7W/jbyf1vRMWwJDWSL+EmtSE8nDZQaUcBabRpPIFJ2g4oxTnro+oUezV8jQjPGdBc5HlfL5t5Fi3WKlmiRRAxJQGgH8LvP7Dh1COjkYFGvk3hD+7OTaJhrK4sk58iXBAj7rwlTTQIv2NRdmYpA/MBUpcSUKkO9+3qNn5gX5iNzi5w3oZn68k0Ucid52dDFLZYg2kXXQF7z7VB67eCw8U/Rsy6JhI='
      device-driver-class-name: com.mysql.cj.jdbc.Driver
      device-url: jdbc:mysql://202.142.28.62:33007/${database.datasource.facedevice.facedevice-dbName}?useSSL=true&serverTimezone=UTC&characterEncoding=utf8&useUnicode=true
      device-username: '{cipher}AQANeaUl85JhUJjxe5gy9vGnqfnvm2p5M0cKqDqAfeOzHvKr3OVgNinnwJZso455XaVMRbgGWhAQra6lzYihhUeJYKHjm4+BF3Onr8hwdH433uF4P28u13IfrG1gjZGbzhst7k3QkW/qggZAFQB6l31lAtT4+0DKj+1HYVz0UIKMhijsVvCaPyw4s8IJnMXWlf6jMLdHoB1LRgWJ21IV7v+UfE4XtZOfQhM3wCL6cGuwj1tfMCcOlgTs1AjUeTUzTAUPX1hXxCviS8JBAhDir2hmGmQxWioAf6e89/1TONLIpknd9aRW5KM4SuQfayQTi1T6m3fyNw9StyDvUezMKsOin2naXFfrnOQhUa+K4aViBXxEoccp+z26ivzmUJTbNGI='
      device-password: '{cipher}AQCB+iRpVT8Lrf6pW9tg6140vcgs9pgMcKoHuhd12Zb5//KdRH1s514+udc+8WARKg48E09C8Z4OV9VeBBPX8N/Sk+TYGuHP9HUG+DlY3OhesnaHz9gqurvkNma/JG1qSHkxR+TKdcFzz62vxrht+ZEAU02lthsBxCzHYcrhv62LbqMhIpHYqC9Hk86HYC0FklqtR8JNbRtb6RprY9jHHe47VNIoyoR4vpIiJvbyFAn2fMsLDKI0+R6AZv7NRYAiE8qY45JK9qIu13//YbWdKJ1jKlL0uOFVSVzx1VsTt/8pguYE5LTwI55tEuTJFATdeAyS84Wdnh9y9uHofMGYDevQIPwsbxUVRzTABhVTEMFjOpH2FEsYFrCIV59ZVcwbouM='
    wechat:
      wechat-dbName: '{cipher}AQAxoI0k4djrnhdrffTg9ILmqhBo6d4XXI/buEBZSszfFde3zJrh4ZMUGl4jRDo3mJGc46tcahJuKkmDOFN0c3RVWD6ieuSd9KVvaNGjKPtg7kZ0phRejDJVI1yCbXSPDUqW6w60dIfYZMELd6tGHnS3bXHTI3I3Knfa75a7W/jbyf1vRMWwJDWSL+EmtSE8nDZQaUcBabRpPIFJ2g4oxTnro+oUezV8jQjPGdBc5HlfL5t5Fi3WKlmiRRAxJQGgH8LvP7Dh1COjkYFGvk3hD+7OTaJhrK4sk58iXBAj7rwlTTQIv2NRdmYpA/MBUpcSUKkO9+3qNn5gX5iNzi5w3oZn68k0Ucid52dDFLZYg2kXXQF7z7VB67eCw8U/Rsy6JhI='
      wechat-driver-class-name: com.mysql.cj.jdbc.Driver
      wechat-url: jdbc:mysql://202.142.28.62:33007/${database.datasource.wechat.wechat-dbName}?useSSL=true&serverTimezone=UTC&characterEncoding=utf8&useUnicode=true
      wechat-username: '{cipher}AQANeaUl85JhUJjxe5gy9vGnqfnvm2p5M0cKqDqAfeOzHvKr3OVgNinnwJZso455XaVMRbgGWhAQra6lzYihhUeJYKHjm4+BF3Onr8hwdH433uF4P28u13IfrG1gjZGbzhst7k3QkW/qggZAFQB6l31lAtT4+0DKj+1HYVz0UIKMhijsVvCaPyw4s8IJnMXWlf6jMLdHoB1LRgWJ21IV7v+UfE4XtZOfQhM3wCL6cGuwj1tfMCcOlgTs1AjUeTUzTAUPX1hXxCviS8JBAhDir2hmGmQxWioAf6e89/1TONLIpknd9aRW5KM4SuQfayQTi1T6m3fyNw9StyDvUezMKsOin2naXFfrnOQhUa+K4aViBXxEoccp+z26ivzmUJTbNGI='
      wechat-password: '{cipher}AQCB+iRpVT8Lrf6pW9tg6140vcgs9pgMcKoHuhd12Zb5//KdRH1s514+udc+8WARKg48E09C8Z4OV9VeBBPX8N/Sk+TYGuHP9HUG+DlY3OhesnaHz9gqurvkNma/JG1qSHkxR+TKdcFzz62vxrht+ZEAU02lthsBxCzHYcrhv62LbqMhIpHYqC9Hk86HYC0FklqtR8JNbRtb6RprY9jHHe47VNIoyoR4vpIiJvbyFAn2fMsLDKI0+R6AZv7NRYAiE8qY45JK9qIu13//YbWdKJ1jKlL0uOFVSVzx1VsTt/8pguYE5LTwI55tEuTJFATdeAyS84Wdnh9y9uHofMGYDevQIPwsbxUVRzTABhVTEMFjOpH2FEsYFrCIV59ZVcwbouM='
    auth:
      auth-dbName: '{cipher}AQAxoI0k4djrnhdrffTg9ILmqhBo6d4XXI/buEBZSszfFde3zJrh4ZMUGl4jRDo3mJGc46tcahJuKkmDOFN0c3RVWD6ieuSd9KVvaNGjKPtg7kZ0phRejDJVI1yCbXSPDUqW6w60dIfYZMELd6tGHnS3bXHTI3I3Knfa75a7W/jbyf1vRMWwJDWSL+EmtSE8nDZQaUcBabRpPIFJ2g4oxTnro+oUezV8jQjPGdBc5HlfL5t5Fi3WKlmiRRAxJQGgH8LvP7Dh1COjkYFGvk3hD+7OTaJhrK4sk58iXBAj7rwlTTQIv2NRdmYpA/MBUpcSUKkO9+3qNn5gX5iNzi5w3oZn68k0Ucid52dDFLZYg2kXXQF7z7VB67eCw8U/Rsy6JhI='
      auth-driver-class-name: com.mysql.cj.jdbc.Driver
      auth-url: jdbc:mysql://202.142.28.62:33007/${database.datasource.auth.auth-dbName}?useSSL=true&serverTimezone=UTC&characterEncoding=utf8&useUnicode=true
      auth-username: '{cipher}AQANeaUl85JhUJjxe5gy9vGnqfnvm2p5M0cKqDqAfeOzHvKr3OVgNinnwJZso455XaVMRbgGWhAQra6lzYihhUeJYKHjm4+BF3Onr8hwdH433uF4P28u13IfrG1gjZGbzhst7k3QkW/qggZAFQB6l31lAtT4+0DKj+1HYVz0UIKMhijsVvCaPyw4s8IJnMXWlf6jMLdHoB1LRgWJ21IV7v+UfE4XtZOfQhM3wCL6cGuwj1tfMCcOlgTs1AjUeTUzTAUPX1hXxCviS8JBAhDir2hmGmQxWioAf6e89/1TONLIpknd9aRW5KM4SuQfayQTi1T6m3fyNw9StyDvUezMKsOin2naXFfrnOQhUa+K4aViBXxEoccp+z26ivzmUJTbNGI='
      auth-password: '{cipher}AQCB+iRpVT8Lrf6pW9tg6140vcgs9pgMcKoHuhd12Zb5//KdRH1s514+udc+8WARKg48E09C8Z4OV9VeBBPX8N/Sk+TYGuHP9HUG+DlY3OhesnaHz9gqurvkNma/JG1qSHkxR+TKdcFzz62vxrht+ZEAU02lthsBxCzHYcrhv62LbqMhIpHYqC9Hk86HYC0FklqtR8JNbRtb6RprY9jHHe47VNIoyoR4vpIiJvbyFAn2fMsLDKI0+R6AZv7NRYAiE8qY45JK9qIu13//YbWdKJ1jKlL0uOFVSVzx1VsTt/8pguYE5LTwI55tEuTJFATdeAyS84Wdnh9y9uHofMGYDevQIPwsbxUVRzTABhVTEMFjOpH2FEsYFrCIV59ZVcwbouM='
    logger:
      logger-dbName: '{cipher}AQAxoI0k4djrnhdrffTg9ILmqhBo6d4XXI/buEBZSszfFde3zJrh4ZMUGl4jRDo3mJGc46tcahJuKkmDOFN0c3RVWD6ieuSd9KVvaNGjKPtg7kZ0phRejDJVI1yCbXSPDUqW6w60dIfYZMELd6tGHnS3bXHTI3I3Knfa75a7W/jbyf1vRMWwJDWSL+EmtSE8nDZQaUcBabRpPIFJ2g4oxTnro+oUezV8jQjPGdBc5HlfL5t5Fi3WKlmiRRAxJQGgH8LvP7Dh1COjkYFGvk3hD+7OTaJhrK4sk58iXBAj7rwlTTQIv2NRdmYpA/MBUpcSUKkO9+3qNn5gX5iNzi5w3oZn68k0Ucid52dDFLZYg2kXXQF7z7VB67eCw8U/Rsy6JhI='
      logger-driver-class-name: com.mysql.cj.jdbc.Driver
      logger-url: jdbc:mysql://202.142.28.62:33007/${database.datasource.logger.logger-dbName}?useSSL=true&serverTimezone=UTC&characterEncoding=utf8&useUnicode=true
      logger-username: '{cipher}AQANeaUl85JhUJjxe5gy9vGnqfnvm2p5M0cKqDqAfeOzHvKr3OVgNinnwJZso455XaVMRbgGWhAQra6lzYihhUeJYKHjm4+BF3Onr8hwdH433uF4P28u13IfrG1gjZGbzhst7k3QkW/qggZAFQB6l31lAtT4+0DKj+1HYVz0UIKMhijsVvCaPyw4s8IJnMXWlf6jMLdHoB1LRgWJ21IV7v+UfE4XtZOfQhM3wCL6cGuwj1tfMCcOlgTs1AjUeTUzTAUPX1hXxCviS8JBAhDir2hmGmQxWioAf6e89/1TONLIpknd9aRW5KM4SuQfayQTi1T6m3fyNw9StyDvUezMKsOin2naXFfrnOQhUa+K4aViBXxEoccp+z26ivzmUJTbNGI='
      logger-password: '{cipher}AQCB+iRpVT8Lrf6pW9tg6140vcgs9pgMcKoHuhd12Zb5//KdRH1s514+udc+8WARKg48E09C8Z4OV9VeBBPX8N/Sk+TYGuHP9HUG+DlY3OhesnaHz9gqurvkNma/JG1qSHkxR+TKdcFzz62vxrht+ZEAU02lthsBxCzHYcrhv62LbqMhIpHYqC9Hk86HYC0FklqtR8JNbRtb6RprY9jHHe47VNIoyoR4vpIiJvbyFAn2fMsLDKI0+R6AZv7NRYAiE8qY45JK9qIu13//YbWdKJ1jKlL0uOFVSVzx1VsTt/8pguYE5LTwI55tEuTJFATdeAyS84Wdnh9y9uHofMGYDevQIPwsbxUVRzTABhVTEMFjOpH2FEsYFrCIV59ZVcwbouM='

