server:
  port: ${server.port.auth}
  tomcat:
    uri-encoding: ${project.encoding.charset}
spring:
  application:
    name: ${server.name.auth}

feign:
  hystrix:
    enabled: true

logging:
    level:
      com:
        itgo:
          auth:
            realize:
              dao: TRACE

#mybatis配置
mybatis:
  config-location: classpath:mybatis-config.xml
  mapperLocations: classpath*:/mapper/**/*.xml

pagehelper:
  helperDialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true

