spring:
  application:
    name: ${server.name.auth}
  datasource:
    driver-class-name: ${database.datasource.auth.auth-driver-class-name}
    url: ${database.datasource.auth.auth-url}
    username: ${database.datasource.auth.auth-username}
    password: ${database.datasource.auth.auth-password}

server:
  port: ${server.port.auth}
  tomcat:
    uri-encoding: ${project.encoding.charset}

feign:
  hystrix:
    enabled: true

com:
  qlhx:
    auth:
      realize:
        mapper: TRACE

mybatis:
  mapperLocations: classpath*:/mappers/*.xml

