spring:
  application:
    name: ${web.name.control}
  resources:
    static-locations: file:D:/aivms5_image
  mvc:
    static-path-pattern: /**

server:
  port: ${web.port.control}
  tomcat:
    uri-encoding: ${project.encoding.charset}