spring:
  application:
    name: ${server.name.device}
  datasource:
    driver-class-name: ${database.datasource.device.driver-class-name}
    url: ${database.datasource.device.url}
    username: ${database.datasource.device.username}
    password: ${database.datasource.device.password}
  resources:
    static-locations: file:D:/aivms5_image
  mvc:
    static-path-pattern: /**

server:
  port: ${server.port.device}
  tomcat:
    uri-encoding: ${project.encoding.charset}

feign:
  hystrix:
    enabled: true

#logging:
#    level:
#        com:
#            itgo:
#                service:
#                    device:
#                        realize:
#                            mapper: TRACE


mybatis:
  mapperLocations: classpath*:/mappers/*.xml

