spring:
  application:
    name: ${server.name.door}
  datasource:
    driver-class-name: ${database.datasource.door.door-driver-class-name}
    url: ${database.datasource.door.door-url}
    username: ${database.datasource.door.door-username}
    password: ${database.datasource.door.door-password}
  resources:
    static-locations: file:D:/aivms5_image
  mvc:
    static-path-pattern: /**
  redis:
    host: ${database.datasource.redis.redis-host}
    port: ${database.datasource.redis.redis-port}
    password: ${database.datasource.redis.redis-password}
    timeout: ${database.datasource.redis.redis-timeout}
    database: ${database.datasource.redis.redis-database}
  rabbitmq:
    host: ${database.datasource.rabbitmq.rabbitmq-host}
    port: ${database.datasource.rabbitmq.rabbitmq-port}
    password: ${database.datasource.rabbitmq.rabbitmq-password}
    username: ${database.datasource.rabbitmq.rabbitmq-username}

server:
  port: ${server.port.door}
  tomcat:
    uri-encoding: ${project.encoding.charset}

feign:
  hystrix:
    enabled: true

#logging:
#    level:
#        com:
#            itgo:
#                service:
#                    door:
#                        realize:
#                            mapper: TRACE


mybatis:
  mapperLocations: classpath*:/mappers/*.xml

