spring:
  application:
    name: ${server.name.facedevice}
  datasource:
    driver-class-name: ${database.datasource.facedevice.facedevice-driver-class-name}
    url: ${database.datasource.facedevice.facedevice-url}
    username: ${database.datasource.facedevice.facedevice-username}
    password: ${database.datasource.facedevice.facedevice-password}
  resources:
    static-locations: file:D:/aivms5_image
  mvc:
    static-path-pattern: /**


server:
  port: ${server.port.facedevice}
  tomcat:
    uri-encoding: ${project.encoding.charset}

feign:
  hystrix:
    enabled: true

#logging:
#    level:
#        com:
#            itgo:
#                service:
#                    facedevice:
#                        realize:
#                            mapper: TRACE


mybatis:
  mapperLocations: classpath*:/mappers/*.xml

