spring:
  application:
    name: ${web.name.gateway}
  resources:
    static-locations: file:D:/aivms5_image
  mvc:
    static-path-pattern: /**
  aop:
    proxy-target-class: true
    auto: true

server:
  port: ${web.port.gateway}
  tomcat:
    uri-encoding: ${project.encoding.charset}