spring:
  application:
    name: ${server.name.logger}
  datasource:
    driver-class-name: ${database.datasource.logger.driver-class-name}
    url: ${database.datasource.logger.url}
    username: ${database.datasource.logger.username}
    password: ${database.datasource.logger.password}
  resources:
    static-locations: file:D:/aivms5_image
  mvc:
    static-path-pattern: /**
  redis:
    host: ${database.datasource.redis.host}
    port: ${database.datasource.redis.port}
    password: ${database.datasource.redis.password}
    timeout: ${database.datasource.redis.timeout}
    database: ${database.datasource.redis.database}
  rabbitmq:
    host: ${database.datasource.rabbitmq.host}
    port: ${database.datasource.rabbitmq.port}
    password: ${database.datasource.rabbitmq.password}
    username: ${database.datasource.rabbitmq.username}

server:
  port: ${server.port.logger}
  tomcat:
    uri-encoding: ${project.encoding.charset}

feign:
  hystrix:
    enabled: true

#logging:
#    level:
#        com:
#            itgo:
#                service:
#                    door:
#                        realize:
#                            mapper: TRACE


mybatis:
  mapperLocations: classpath*:/mappers/*.xml

